# fly.toml app configuration file generated for biscuits-club on 2024-03-26T20:58:17-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'biscuits-club'
primary_region = 'iad'

[build]
image = "ghcr.io/a-type/biscuits:main"

[env]
PORT = "6124"
MAKE_PRODUCT_ADMIN = "gaforres@gmail.com"
EMAIL_USER = "hi@biscuits.club"
UI_ORIGIN = "https://biscuits.club"
DATABASE_FILE = "/data/database.sqlite"
STORAGE_DATABASE_FILE = "/data/storage.sqlite"
STORAGE_DATABASES_DIRECTORY = "/data/storage"
HOST = "https://api.biscuits.club"
NODE_ENV = "production"

[http_service]
internal_port = 6124
force_https = true
auto_stop_machines = "suspend"
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[http_service.concurrency]
type = "connections"
hard_limit = 10000
soft_limit = 10000

[[http_service.checks]]
interval = "10s"
grace_period = "5s"
method = "get"
path = "/"
protocol = "http"
restart_limit = 0
timeout = "2s"
tls_skip_verify = false

[[mounts]]
source = "biscuits_data"
destination = "/data"
initial_size = "3GB"
auto_extend_size_threshold = 80
auto_extend_size_increment = "1GB"
auto_extend_size_limit = "10GB"

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
