packages:
  - 'web'
  - 'server'
  - 'packages/*'
  - 'apps/**/*'
  - 'workers/**/*'
  - 'blog'
  - 'cdk'

catalog:
  '@a-type/ui': '^4.1.7'
  '@a-type/utils': ^1.1.9
  '@a-type/auth-fetch': 2.1.3
  '@a-type/auth-ui': 1.1.0
  '@a-type/auth': 1.3.16
  '@originjs/vite-plugin-commonjs': 1.0.3
  '@react-spring/web': 10.0.3
  '@verdant-web/cli': 5.1.0
  '@verdant-web/react': 43.0.0
  '@verdant-web/react-router': 0.8.0
  '@verdant-web/store': 5.0.2
  '@verdant-web/server': 4.0.3
  '@verdant-web/s3-file-storage': 1.0.42
  '@verdant-web/tiptap': 7.0.2
  '@verdant-web/cloudflare': 0.1.6
  '@vitejs/plugin-react-swc': 4.2.2
  '@vitejs/plugin-react': 5.1.2
  gql.tada: 1.9.0
  react: 19.2.3
  react-dom: 19.2.3
  '@types/react': ^19.2.8
  '@types/react-dom': ^19.2.3
  typescript: 5.9.3
  unocss: 66.5.12
  '@unocss/transformer-variant-group': 66.5.12
  valtio: ^2.1.8
  vite: ^7.3.1
  vite-plugin-pwa: ^1.2.0
  workbox-core: ^7.4.0
  workbox-expiration: ^7.4.0
  workbox-precaching: ^7.4.0
  workbox-routing: ^7.4.0
  workbox-strategies: ^7.4.0
  workbox-window: ^7.4.0
  eslint: 9.39.2
  eslint-plugin-react: 7.37.5
  '@eslint/js': 9.37.0
  eslint-plugin-react-hooks: 7.0.0
  typescript-eslint: 8.46.0
  '@tiptap/core': 2.11.5
  '@tiptap/starter-kit': 2.11.5
  '@tiptap/react': 2.11.5
  '@tiptap/pm': 2.11.5
  '@tiptap/extension-link': 2.11.5
  '@tiptap/extension-document': 2.11.5
  '@tiptap/extension-paragraph': 2.11.5
  '@tiptap/extension-placeholder': 2.11.5
  '@tiptap/extension-typography': 2.11.5
  '@tiptap/html': 2.11.5
  date-fns: 4.1.0
  wrangler: 4.58.0
  '@types/node': ^22
  cookie: ^1.0.2
  babel-plugin-react-compiler: ^1.0.0
  motion: ^12.23.24
  zod: ^4.1.12
  '@cloudflare/vite-plugin': ^1.20.1
  '@tanstack/react-query': ^5.90.16
  '@tanstack/react-router': ^1.147.3
  '@tanstack/react-router-devtools': ^1.149.0
  '@tanstack/react-router-ssr-query': ^1.147.3
  '@tanstack/react-start': ^1.149.0
  graphql-request: ^7.4.0
  vite-tsconfig-paths: ^6.0.4
  '@vite-pwa/assets-generator': ^1.0.2
  '@use-gesture/react': 10.3.1
  vitest: ^4.0.17
  cheerio: 1.1.2
  robots-parser: ^3.0.1
  iso8601-duration: ^2.1.3
