packages:
  - 'web'
  - 'server'
  - 'packages/*'
  - 'apps/**/*'
  - 'workers/**/*'
  - 'blog'
  - 'cdk'

catalog:
  '@a-type/ui': 2.1.13
  '@a-type/utils': 1.1.4
  '@originjs/vite-plugin-commonjs': 1.0.3
  '@react-spring/web': 9.7.5
  '@verdant-web/cli': 4.8.2
  '@verdant-web/react': 42.1.0
  '@verdant-web/react-router': 0.7.2
  '@verdant-web/store': 4.4.1
  '@verdant-web/server': 3.3.11
  '@verdant-web/s3-file-storage': 1.0.38
  '@verdant-web/tiptap': 4.1.1
  '@vitejs/plugin-react-swc': 3.7.2
  gql.tada: 1.8.10
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.8.3
  unocss: 66.0.0
  '@unocss/transformer-variant-group': 66.0.0
  valtio: ^2.1.2
  vite: ^6.0.3
  vite-plugin-pwa: ^0.21.1
  workbox-core: ^7.3.0
  workbox-expiration: ^7.3.0
  workbox-precaching: ^7.3.0
  workbox-routing: ^7.3.0
  workbox-strategies: ^7.3.0
  workbox-window: ^7.3.0
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0
  '@a-type/auth-fetch': 2.0.0
  '@a-type/auth-ui': 1.0.15
  '@a-type/auth': 1.3.11
  eslint: 9.20.1
  eslint-plugin-react: 7.37.4
  '@eslint/js': 9.20.0
  eslint-plugin-react-hooks: 5.1.0
  typescript-eslint: 8.24.1
  '@tiptap/core': 2.11.5
  '@tiptap/starter-kit': 2.11.5
  '@tiptap/react': 2.11.5
  '@tiptap/pm': 2.11.5
  '@tiptap/extension-link': 2.11.5
  '@tiptap/extension-document': 2.11.5
  '@tiptap/extension-paragraph': 2.11.5
  '@tiptap/extension-placeholder': 2.11.5
  '@tiptap/extension-typography': 2.11.5
  '@tiptap/html': 2.11.5
  date-fns: 4.1.0
