packages:
  - 'web'
  - 'server'
  - 'packages/*'
  - 'apps/**/*'
  - 'workers/**/*'
  - 'blog'
  - 'cdk'

catalog:
  '@a-type/ui': 2.8.12
  '@a-type/utils': 1.1.5
  '@a-type/auth-fetch': 2.1.3
  '@a-type/auth-ui': 1.1.0
  '@a-type/auth': 1.3.16
  '@originjs/vite-plugin-commonjs': 1.0.3
  '@react-spring/web': 9.7.5
  '@verdant-web/cli': 4.8.3
  '@verdant-web/react': 42.1.1
  '@verdant-web/react-router': 0.8.0
  '@verdant-web/store': 4.6.1
  '@verdant-web/server': 4.0.3
  '@verdant-web/s3-file-storage': 1.0.42
  '@verdant-web/tiptap': 6.0.1
  '@verdant-web/cloudflare': 0.1.5
  '@vitejs/plugin-react-swc': 4.1.0
  '@vitejs/plugin-react': 5.0.4
  gql.tada: 1.8.13
  react: 19.2.0
  react-dom: 19.2.0
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.1
  typescript: 5.9.3
  unocss: 66.5.3
  '@unocss/transformer-variant-group': 66.5.3
  valtio: ^2.1.8
  vite: ^7.1.9
  vite-plugin-pwa: ^1.0.3
  workbox-core: ^7.3.0
  workbox-expiration: ^7.3.0
  workbox-precaching: ^7.3.0
  workbox-routing: ^7.3.0
  workbox-strategies: ^7.3.0
  workbox-window: ^7.3.0
  eslint: 9.37.0
  eslint-plugin-react: 7.37.5
  '@eslint/js': 9.37.0
  eslint-plugin-react-hooks: 7.0.0
  typescript-eslint: 8.46.0
  '@tiptap/core': 2.11.5
  '@tiptap/starter-kit': 2.11.5
  '@tiptap/react': 2.11.5
  '@tiptap/pm': 2.11.5
  '@tiptap/extension-link': 2.11.5
  '@tiptap/extension-document': 2.11.5
  '@tiptap/extension-paragraph': 2.11.5
  '@tiptap/extension-placeholder': 2.11.5
  '@tiptap/extension-typography': 2.11.5
  '@tiptap/html': 2.11.5
  date-fns: 4.1.0
  wrangler: 4.42.2
  '@cloudflare/workers-types': ^4.20251011.0
  '@types/node': ^22

  cookie: ^1.0.2
  babel-plugin-react-compiler: ^1.0.0
