packages:
  - 'web'
  - 'server'
  - 'packages/*'
  - 'apps/**/*'
  - 'blog'
  - 'cdk'

catalog:
  '@a-type/ui': 1.5.5
  '@a-type/utils': 1.1.4
  '@originjs/vite-plugin-commonjs': 1.0.3
  '@react-spring/web': 9.7.5
  '@unocss/transformer-variant-group': ^0.65.2
  '@verdant-web/cli': 4.7.2
  '@verdant-web/react': 40.2.1
  '@verdant-web/react-router': 0.7.1
  '@verdant-web/store': 4.1.2
  '@vitejs/plugin-react-swc': 3.7.2
  gql.tada: 1.8.10
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.7.2
  unocss: ^0.65.2
  valtio: ^2.1.2
  vite: ^6.0.3
  vite-plugin-pwa: ^0.21.1
  workbox-core: ^7.3.0
  workbox-expiration: ^7.3.0
  workbox-precaching: ^7.3.0
  workbox-routing: ^7.3.0
  workbox-strategies: ^7.3.0
  workbox-window: ^7.3.0
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0
  '@a-type/auth-fetch': 1.0.2
  '@a-type/auth-ui': 1.0.15
  '@a-type/auth': 1.3.9
