/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import { useRef } from 'react';
import * as THREE from 'three';
// @ts-ignore
import { animated } from '@react-spring/three';
import { GLTF } from 'three-stdlib';
import { darkGreen, green, white } from '../materials.js';

type GLTFResult = GLTF & {
	nodes: {
		Mesh_leek: THREE.Mesh;
		Mesh_leek_1: THREE.Mesh;
		Mesh_leek_2: THREE.Mesh;
	};
	materials: {
		green: THREE.MeshStandardMaterial;
		_defaultMat: THREE.MeshStandardMaterial;
		greenDark: THREE.MeshStandardMaterial;
	};
};

export function Leek({ ...props }: JSX.IntrinsicElements['group']) {
	const group = useRef<THREE.Group>(null);
	const { nodes, materials } = useGLTF(
		'/models/kenney-foods/leek.glb',
	) as GLTFResult;
	return (
		<animated.group ref={group} {...props} dispose={null}>
			<mesh castShadow geometry={nodes.Mesh_leek.geometry} material={green} />
			<mesh castShadow geometry={nodes.Mesh_leek_1.geometry} material={white} />
			<mesh
				castShadow
				geometry={nodes.Mesh_leek_2.geometry}
				material={darkGreen}
			/>
		</animated.group>
	);
}

// useGLTF.preload('/models/kenney-foods/leek.glb');
