/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import { useRef } from 'react';
import * as THREE from 'three';
// @ts-ignore
import { animated } from '@react-spring/three';
import { GLTF } from 'three-stdlib';
import { lightBrown } from '../materials.js';

type GLTFResult = GLTF & {
	nodes: {
		onion: THREE.Mesh;
	};
	materials: {
		brown: THREE.MeshStandardMaterial;
	};
};

export function Garlic({ ...props }: JSX.IntrinsicElements['group']) {
	const group = useRef<THREE.Group>(null);
	const { nodes, materials } = useGLTF(
		'/models/kenney-foods/smoothed/onion.glb',
	) as GLTFResult;
	return (
		<animated.group ref={group} {...props} dispose={null}>
			<mesh
				scale={[0.8, 0.6, 0.8]}
				castShadow
				geometry={nodes.onion.geometry}
				material={lightBrown}
			/>
		</animated.group>
	);
}

useGLTF.preload('/models/kenney-foods/smoothed/onion.glb');
