/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ListIdRouteImport } from './routes/$listId'

const ListIdRoute = ListIdRouteImport.update({
  id: '/$listId',
  path: '/$listId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$listId': typeof ListIdRoute
}
export interface FileRoutesByTo {
  '/$listId': typeof ListIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$listId': typeof ListIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$listId'
  fileRoutesByTo: FileRoutesByTo
  to: '/$listId'
  id: '__root__' | '/$listId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ListIdRoute: typeof ListIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$listId': {
      id: '/$listId'
      path: '/$listId'
      fullPath: '/$listId'
      preLoaderRoute: typeof ListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ListIdRoute: ListIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
