name: Update Infrastructure

on:
  push:
    branches:
      - main

jobs:
  update_infrastructure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.12.1

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --filter @biscuits/cdk...

      - name: Deploy infrastructure
        run: pnpm cdk deploy --require-approval never
        working-directory: cdk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
