name: Star chart deploy
on:
  push:
    branches: [main]
    paths:
      - 'apps/star-chart/**'
      - 'packages/client/**'
      - '.github/workflows/deploy-star-chart.yml'

jobs:
  build-and-deploy-star-chart:
    name: Build and deploy star-chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.12.1

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --filter @star-chart.biscuits/web...

      - name: Build star-chart
        run: pnpm --filter @star-chart.biscuits/web... run build
        env:
          VITE_API_ORIGIN: ${{ vars.API_ORIGIN }}
          VITE_HOME_ORIGIN: ${{ vars.HOME_ORIGIN }}
          VITE_PUBLIC_URL: https://star-chart.biscuits.club

      - name: Deploy star-chart to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ vars.S3_BUCKET_STAR_CHART }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOYER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOYER_AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: './apps/star-chart/web/dist'

      - name: Invalidate CloudFront cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOYER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOYER_AWS_SECRET_ACCESS_KEY }}
          DISTRIBUTION: ${{ vars.CLOUDFRONT_ID_STAR_CHART }}
          PATHS: '/*'
          AWS_REGION: 'us-east-1'
