name: Star chart deploy
on:
  push:
    branches: [main]
    paths:
      - 'apps/star-chart/**'
      - 'packages/client/**'
      - 'packages/apps/**'
      - '.github/workflows/deploy-star-chart.yml'
      - 'pnpm-workspace.yaml'

jobs:
  build-and-deploy-star-chart:
    name: Build and deploy star-chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 9.15.2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '22'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --filter @star-chart.biscuits/web...

      - name: Build star-chart
        run: pnpm --filter @star-chart.biscuits/web... run build
        env:
          VITE_API_ORIGIN: ${{ vars.API_ORIGIN }}
          VITE_HOME_ORIGIN: ${{ vars.HOME_ORIGIN }}
          VITE_PUBLIC_URL: https://star-chart.biscuits.club
          VITE_STRIPE_PUBLISHABLE_KEY: ${{ vars.STRIPE_PUBLISHABLE_KEY }}

      - name: Deploy star-chart to S3
        uses: jakejarvis/s3-sync-action@7ed8b112447abb09f1da74f3466e4194fc7a6311
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ vars.S3_BUCKET_STAR_CHART }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOYER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOYER_AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: './apps/star-chart/web/dist'

      - name: Invalidate CloudFront cache
        uses: chetan/invalidate-cloudfront-action@c384d5f09592318a77b1e5c0c8d4772317e48b25
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOYER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOYER_AWS_SECRET_ACCESS_KEY }}
          DISTRIBUTION: ${{ vars.CLOUDFRONT_ID_STAR_CHART }}
          PATHS: '/*'
          AWS_REGION: 'us-east-1'
