name: Gnocchi Share deploy
on:
  push:
    branches: [main]
    paths:
      - "apps/gnocchi/share/**"
      - ".github/workflows/deploy-worker-gnocchi-share.yml"
      - "pnpm-workspace.yaml"

jobs:
  build-and-deploy-gnocchi-share:
    name: Build and deploy gnocchi-share
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
        with:
          version: 9.15.2
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --filter @gnocchi.biscuits/share...

      - name: Build app
        run: pnpm build --filter @gnocchi.biscuits/share...

      - name: Verify cloudflare token
        run: |
          curl -X GET "https://api.cloudflare.com/client/v4/user/tokens/verify" \
          -H "Authorization: Bearer ${{secrets.CLOUDFLARE_API_TOKEN}}" \
          -H "Content-Type:application/json"

      - name: Deploy app
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy
          packageManager: pnpm
          workingDirectory: ./apps/gnocchi/share
