name: Wishwash Deploy
on:
  push:
    branches: [main]
    paths:
      - 'apps/wish-wash/**'
      - 'packages/client/**'
      - 'packages/apps/**'
      - '.github/workflows/deploy-wish-wash.yml'

jobs:
  build-and-deploy-wish-wash:
    name: Build and deploy wish-wash
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 9.15.2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --filter @wish-wash.biscuits/web...

      - name: Build wish-wash
        run: pnpm --filter @wish-wash.biscuits/web... run build
        env:
          VITE_API_ORIGIN: ${{ vars.API_ORIGIN }}
          VITE_HOME_ORIGIN: ${{ vars.HOME_ORIGIN }}
          VITE_PUBLIC_URL: https://wish-wash.biscuits.club
          VITE_STRIPE_PUBLISHABLE_KEY: ${{ vars.STRIPE_PUBLISHABLE_KEY }}

      - name: Deploy wish-wash to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ vars.S3_BUCKET_WISH_WASH }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOYER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOYER_AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: './apps/wish-wash/web/dist'

      - name: Invalidate CloudFront cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOYER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOYER_AWS_SECRET_ACCESS_KEY }}
          DISTRIBUTION: ${{ vars.CLOUDFRONT_ID_WISH_WASH }}
          PATHS: '/*'
          AWS_REGION: 'us-east-1'
