name: Star chart deploy
on:
  push:
    branches: [main]
    paths:
      - 'apps/star-chart/**'
      - 'packages/client/**'
      - 'packages/apps/**'
      - '.github/workflows/deploy-star-chart.yml'
      - 'pnpm-workspace.yaml'

jobs:
  build-and-deploy-star-chart:
    name: Build and deploy star-chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        with:
          version: 9.15.2
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --filter @star-chart.biscuits/web...

      - name: Build star-chart
        run: pnpm --filter @star-chart.biscuits/web... run build
        env:
          VITE_API_ORIGIN: ${{ vars.API_ORIGIN }}
          VITE_HOME_ORIGIN: ${{ vars.HOME_ORIGIN }}
          VITE_PUBLIC_URL: https://star-chart.biscuits.club
          VITE_STRIPE_PUBLISHABLE_KEY: ${{ vars.STRIPE_PUBLISHABLE_KEY }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Verify cloudflare token
        run: |
          curl -X GET "https://api.cloudflare.com/client/v4/user/tokens/verify" \
          -H "Authorization: Bearer ${{secrets.CLOUDFLARE_API_TOKEN}}" \
          -H "Content-Type:application/json"

      - name: Deploy app
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy dist --project-name=prod-biscuits-star-chart-app
          packageManager: pnpm
          workingDirectory: ./apps/star-chart/web
